### ISSUE TITLE
Add track circuit based simulation option

### ISSUE THREAD

**Issue by npiganeau** [ts2/ts2#10]
Until now, the trains are shown on the scenery at their exact position. This is not realistic since real signallers only get approximate train position through track circuits. Add an option so that the user can decide whether to show the train's real position as it is now or only the activated track circuits. The latter will need the simulation to be created with a line item per track circuit.

**Comment by pedromorgan** [comment]
This is open.. its on the to do right ;-))

 Anyone wanna code this please ??

**Comment by npiganeau** [comment]
This is done already. When playing a sim, go to file, properties and check play with track circuits. You can also set it in the general tab of the editor.
