### ISSUE TITLE
Manage several routes between same signal

### ISSUE THREAD

**Issue by npiganeau** [ts2/ts2#100]
Probably have a priority between routes to select the first one that is not yet activated

**Comment by Sharpe49** [comment]
I have started the French MISTRAL interface.

![2019-12-07 21_08_32-Train Signalling Simulator _ Image de service MISTRAL](https://user-images.githubusercontent.com/375720/71326997-0b200980-2503-11ea-9e0f-abbcbac4bc05.png)

For routes with the same origin (3609) and same destination (3623), I need to be able to define a waypoint.
For example, if I have two routes, one going through waypoint A, the other going through waypoint B, I will use the command 21 3609 3623 A or 21 3609 3623 B

**Comment by npiganeau** [comment]
I suggest you do the same as I did in the client. That is you consider the first route between the same signals as A (ordered by for number), then B, etc. 
On the simulation file/editor, you set route A before true B so that it has a smaller route number.
