### ISSUE TITLE
PyQt Problems

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#18]
I'm guite curious to run this project as with pyqt on Linux/kubuntu

Snag is on Kununtu its python2/qt4 or python3/qt5 ( running pyqt4 on python3 is not in distrubution )

So not sure how to get around this.. but am prepared to help, maybe first step if to make it run on python2+3 which doable... and maybe later step up to pyqt5 ??

pete

**Comment by pedromorgan** [comment]
ok so got a first branc in pyqthon2.7 adn its sucks..

need to replace all the super() signatures etc..
and pyqt4 is kinda EOL..
https://github.com/pedromorgan/ts2/commit/a34b52dae3ac9fb5feb430f4d0967b8424b17bc6

So then try qt5

**Comment by pedromorgan** [comment]
Got a qt5 branch
https://github.com/pedromorgan/ts2/commits/qt5

Main change is to use Qt.py
https://github.com/pedromorgan/ts2/blob/qt5/ts2/Qt.py
and idea nicked from pyqtchart

so we could potentiall, stick in pyside here also

Can help if you wish to pursue qt5 path

**Comment by npiganeau** [comment]
Hi Pete,

Thanks for your interest in ts2. Yes, let's go for python3/qt5. The only reason it is on qt4 is that pyqt didn't support qt5 on python 3 at the time I started developing.

Unfortunately, I don't have any time to do that, but I will review and pull all PR you could make.

**Comment by pedromorgan** [comment]
Initial PR
https://github.com/npiganeau/ts2/pull/21

**Comment by pedromorgan** [comment]
Can we close this ?? 
Can I have perms so I can classify some of these issues please..

**Comment by npiganeau** [comment]
Ok. 

I moved the repository to github.com/ts2 so you have all rights too.
