### ISSUE TITLE
Save Settings

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#23]
Allow user to save 
- the column position in tables
- the splitter positions
- the dock positions
- window state and size

**Comment by npiganeau** [comment]
Reference documentation: http://doc.qt.io/qt-5/qmainwindow.html#saveState

**Comment by pedromorgan** [comment]
Working on this patch,,  saves the "dock" positions etc also

**Comment by npiganeau** [comment]
@pedromorgan You can close this one once you merged

**Comment by pedromorgan** [comment]
https://github.com/ts2/ts2/pull/51
