### ISSUE TITLE
Project ts2

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#32]
Hi @npiganeau 

Apologoes if I jumped the gun, but am ahcking away..

And gone and created a ts2 project on github
https://github.com/ts2

The idea is that we can have the "desktop" = ts2,
but also 
- ts2/ts2-data
- ts2/ts2-webserver
- ts2/ts2-tutorials

So have some ideas in mind...
includign mainly getting away from sf.net,
and moving stuff to github...
we need more adoptions.. so main motive.. and cos its cool ;-)

hope u dont mind
pedro

**Comment by npiganeau** [comment]
Hi @pedromorgan ,

I just released v0.5 because there was a lot of almost done job there, notably in the editor and with the new signals. I did not have time to do all I wanted, but at least now I can focus on other points.

Concerning the project ts2, I am not against it, but the reason why I am still on sourceforge is that it gives ts2 a good visibility on Google thanks to its being there since 2008. I agree that Github is much better for development and that's why I moved the source code here.

As far as adoption is concerned, I think that what we need is :
1. More simulations to get more players, so we need simulation writers. The new editor is much better for doing this, so that is going the good way.
2. Docs, tutorials, videos, etc.
3. A cool website

Mostly what you wrote actually, but I'll insist on the order of importance. I really think we need more simulations first.

**Comment by pedromorgan** [comment]
Cool stuff.. 
Hopefulyl I'll have some time next to merge into the Qt5 branch..

**Comment by Sharpe49** [comment]
Hi,

Since there is a need for new simulations, I'll try to create a French one.

Cédric

**Comment by npiganeau** [comment]
@Sharpe49 
Hi Cédric,

Welcome onboard ! Do not hesitate to ask any question you can have when you make your simulation.

NPi

**Comment by pedromorgan** [comment]
Here's first stage of the "docs" and this is generated from source..

http://docs-ts2.rhcloud.com/

**Comment by pedromorgan** [comment]
@npiganeau Can we add @Sharpe49  to contribs ?

**Comment by pedromorgan** [comment]
Latest idea now we on GH not sf..

https://ts2.github.io/

**Comment by pedromorgan** [comment]
Have updated https://ts2.github.io/

At least its a start..
Next step is www site so we can "share data"...

Pedro

**Comment by npiganeau** [comment]
Nice ! I like it !

I'll redirect from ts2.sf.net to ts2.github.io so that all users get to the new site !

**Comment by npiganeau** [comment]
Otherwise, I was thinking that we should move all issues related to website to ts2.github.io, issues related to sims or projects of new sims to ts2-data etc. So that we keep here only issues related to the coding of software: wishlist, bugs, etc.

**Comment by pedromorgan** [comment]
Yep.. sound good to me..

>>> Main issue is how to deal with releases...

**Comment by pedromorgan** [comment]
Looking at this also  idea is have a simple www front end, and ts2-data.git as backend.. ie a kinda database/flatfile
https://developer.github.com/v3/repos/contents/

**Comment by npiganeau** [comment]
Why not, it should work. 

Ideally, we should also have a 'get new sims' feature directly inside ts2 that would connect to the front end and enable to browse through the sims from inside the app and with an 'download & play' button next to each one. This way we could also easily implement a dependency mechanism if necessary.

**Comment by npiganeau** [comment]
@pedromorgan Please do not add people to owners of ts2 project but rather to the other teams depending on their contribution. Thanks !

**Comment by mcgiwer** [comment]
@npiganeau Who's the creator of the ts2 project? I'm confused now...

**Comment by npiganeau** [comment]
I am the writer of software itself (see copyright notice). Contributions are welcomed, but I wish to keep an eye on what is merged, so please make pull requests.

@pedromorgan created the project on github, the website, the data repository, the doc website, etc. He is also a code contributor and brainstormer to bring in new ideas to keep this project alive. 

Before he joined, ts2 was alive about one month every two years :-) now we can say we have a real project thanks to him !

**Comment by mcgiwer** [comment]
@npiganeau From what you write, above, @pedromorgan is technically he's the main administrator of the GitHub ts2 project and this is kinda wird that you tell him who he can or cannot add...

**Comment by pedromorgan** [comment]
We are there ;-))))
letz move on @npiganeau ;-)
