### ISSUE TITLE
Not working under Ubuntu 14.04 with pyqt5

### ISSUE THREAD

**Issue by mcgiwer** [ts2/ts2#36]
I have the latest avaliable (from the the latest repository for Ubuntu 14.04) PyQt installed (pyqt5) and when I try to start ts2, I get a error:

$ ./ts2.py or $python ./ts2.py

`Traceback (most recent call last):
  File "./ts2.py", line 23, in <module>
    import ts2.application
  File "/media/ubuntu/tmp/dane/train/ts2-0.5.0/ts2/application.py", line 21, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named 'PyQt4'
`

**Comment by npiganeau** [comment]
Current version of TS2 only works with PyQt4. You need to install the python-qt4 module in ubuntu.

**Comment by mcgiwer** [comment]
wouldn't it a better solution to make that the TS2 self detect the installed PyQt version and import from it the needed libraries or allow to import libraries from PyQt 4 and above?

**Comment by npiganeau** [comment]
Actually pyqt4 and pyqt5 are source incompatible. The current version is written for PyQt4 but the next version has been ported to PyQt5 (and thus will be incompatible with PyQt4).

**Comment by pedromorgan** [comment]
Add more detail as the person who kinda started pyqt5  9and we cant go backwards cos of API changes)..

One of the changes is a Qt.py file...
And the inspiration for this is from pyqtgraph..
and the idea there is to load pyqt5 or pyside etc..
pyside is kinda moving to qt5 it breaks..

https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/Qt.py

**Comment by mcgiwer** [comment]
Any idea when the version for the actual (QT5+) could get avaliable?

**Comment by npiganeau** [comment]
No idea at all ! I develop TS2 when I have time, and it can be years before several versions or just a few months, it depends.

However, if you just need a version that works with PyQt5, you can try to checkout and run commit 56aa3015862f309dbcec09b3b62b68cee24770c7 which should be the current version just ported to PyQt5. It should work, but being an work-in-progress commit, there may be some bugs here and there.

**Comment by pedromorgan** [comment]
So i'm running on Ubuntu here with PyQt5

You need the `develop` branch as that is Qt5

**Comment by pedromorgan** [comment]
@mcgiwer Can u report back tat u using python3 and pyqt5 ?

Wanna nail this because there is confusion with qt5/qt4..

**Comment by mcgiwer** [comment]
@pedromorgan Yes, I use this kind of configuration. Python3 and pyqt5 are the latest avaliable ones for my Ubuntu

**Comment by pedromorgan** [comment]
@mcgiwer Pyqt and pyside are bindings to the underlying c++ API, so thank the angels above that this is not c++ code.. qt5 fixed a lot of issues with qt4... hence a bump
Anyway pyqt5==Qt5 and Python3 is the future
Incidentally pyside which is the pyqt alternate is not even qt5 yet (and maintained by Qtproject)..

So its a long story.. but as a developer I have two configs...on this machine
pyqt5+python3
or
pyqt4+python2.7+

Are u a hacker ??

**Comment by mcgiwer** [comment]
it's good that they fixed bugs of Qt and PyQt, but they shouldn't make any issued with backward compatibility. Acording to my knowledge, all programming languages have some backward compatibility (like by example C++, Perl, Python) and I don't see why Qt and PyQt couldn't have one too.

> Are u a hacker ??

no and y programming skills aren't on enough level to help with developing of ts2. I can try to help other way, by example by testing, sending feedback and ideas

**Comment by pedromorgan** [comment]
@mcgiwer is it workign now ??

**Comment by mcgiwer** [comment]
@pedromorgan 
No, I get following output:

$ ./ts2.py 

Traceback (most recent call last):
  File "./ts2.py", line 23, in <module>
    import ts2.application
  File "/media/ubuntu/tmp/dane/ts2-master/ts2/application.py", line 21, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named 'PyQt4'

**Comment by mcgiwer** [comment]
UPDATE:

after changing in most files from PyQt4 to PyQt5, I got partially rid of the PyQt4 problem, but I get following output:

$ ./ts2.py

Traceback (most recent call last):
  File "./ts2.py", line 23, in <module>
    import ts2.application
  File "/media/ubuntu/tmp/dane/ts2-master/ts2/application.py", line 23, in <module>
    from ts2 import mainwindow
  File "/media/ubuntu/tmp/dane/ts2-master/ts2/mainwindow.py", line 24, in <module>
    from ts2 import simulation, utils
  File "/media/ubuntu/tmp/dane/ts2-master/ts2/simulation.py", line 26, in <module>
    from ts2 import utils, routing, trains
  File "/media/ubuntu/tmp/dane/ts2-master/ts2/routing/__init__.py", line 21, in <module>
    from ts2.routing.position import Position, PositionGraphicsItem
  File "/media/ubuntu/tmp/dane/ts2-master/ts2/routing/position.py", line 25, in <module>
    class PositionGraphicsItem(QtGui.QGraphicsPolygonItem):
AttributeError: 'module' object has no attribute 'QGraphicsPolygonItem'

== End of output ==

**Comment by pedromorgan** [comment]
Ok ok.. Am getting confused..
I'm here on Ubuntu with develop branch mainly..

What u running there and what is the "download ???

want to get to the bottom of this so u can get it running..

BTW we are doing a bit change in the TS" project where we are..
- moving to pyqt5+pytyhon3 mandatoraly
- serialising data to json and intendint to set up a website sson to share
- and moving from sourforge to github.. (unfortunate but sf is down in the
books atmo ;-)))

We are also looking at "aoutobuilding".. ie each change to "master branch"
or "develop" branch
would cause end user like u to be a muppet..
and shout down and sort these props out..

So you input is mega apperciated..
even though I am here with an olde linux box. a virtual 32 bit and
an android and RPI and arudino and alike..

Keep complainging till I hear.

"Light is Green".. ;-)))))))))))))))))))))))

Or whatever.. please.. ta..

**Comment by mcgiwer** [comment]
the branch on with I had done changes afte downloading on hard disk was the one from the main branch on GitHub :)

**Comment by pedromorgan** [comment]
Can u get on irc.freenode.net#trainsig2

**Comment by pedromorgan** [comment]
I want to establish which version your on.. and what windows version...

I kinda got a virtual machine here so wanna taest againt that..

At first though.. 
we are into pyqt5 land so pyqt4 is not the future..

So maybe your python version is wrong or something alike..

Even on kubuntu here and debian servers it catches me out as I am stillin python=2.7+ rather than python3..

That is why I am switching to golang and elimiates external dependancies.. 

and 50+ last last week.. this stuff still pisses me off.. So i want to get down to the "root cause"

So I am with you ;-)))))))))

**Comment by mcgiwer** [comment]
I use only Linux (Ubuntu 14.04) with:

* Python 2.7.6
* python3-pyqt5

**Comment by pedromorgan** [comment]
Thats an oops...

We are onto
Python3....
and pyqt5..

And develop branch ... is what I am using..

U cheching out download with git..
or a binary.. zip etc..

**Comment by mcgiwer** [comment]
@pedromorgan 
You has missunderstand me earlier... the python3 was a part of PyQt package name... Python version is above 3  is avaliable for Ubuntu but only from version 14.10. For 14.04 (with I use), the latest one is 2.7

**Comment by pedromorgan** [comment]
Yes I do.. worry get on chat at
irc.freenode.org#trainsig2

**Comment by pedromorgan** [comment]
Ok Pyqt4 is out..

I did some of the "tranistion code" for moving to PyQt5
So the platform is
- python3
- pyqt5
previous was
- python 2.7
- pyqt4

We are adopting the python3 and pyqt5

**Comment by pedromorgan** [comment]
Ypipee new irc channel#
irc.freenode.net#trainsig#2

**Comment by pedromorgan** [comment]
Ok new chat line

irc.freenode.net/trainsig2
;-))

**Comment by npiganeau** [comment]
@mcgiwer 
Let's make it simple:
- TS2 does not work with Python 2 you need Python 3.3 or above (which is shipped with ubuntu 14.04, no pb. Just ```ll /usr/bin/python``` to check which version will run if you run when typing ```python``` as several versions can be installed side by side. Run ```python3.4``` (on 14.04) instead of ```python``` to run python 3 for sure)
- Either you have Python 3 + python3-qt4 then use code from master branch
- Either you have Python 3 + python3-qt5 then use code from develop branch

**Comment by mcgiwer** [comment]
@npiganeau I have updated my python and have now Python 3.4.3 + python3-pyqt5

**Comment by npiganeau** [comment]
That is the same config as I have.

It won't work with master branch, checkout develop branch

**Comment by mcgiwer** [comment]
@npiganeau Please stop removing the code updates I do

**Comment by npiganeau** [comment]
@mcgiwer as explained in #32, contributions are welcome but please submit them as pull requests.

**Comment by mcgiwer** [comment]
@npiganeau I do that as a pull request

**Comment by mcgiwer** [comment]
@npiganeau Could you see my work on the ts2 at: https://github.com/mcgiwer/ts2 ? I did there some iomprovements in the code, like:

+ added a PyQt selector script ( pyqt.py ) with discovers if there is PyQt4 or PyQt5 installed and imports the QtCore and QtGui libs.

+ modified that the ts2 code refers itself to the selector script to use the imported by it PyQt libs

**Comment by npiganeau** [comment]
@mcgiwer Ok. Actually, this is slightly more complex since the name spaces have been modified between Qt4 and Qt5. For instance, all widgets have been transfered from QtGui to QtWidgets, some classes have been transfered from QtGui to QtCore or vice-versa, etc. Also, some function that are used in ts2 have been deprecated.

That is why we decided not to support both PyQt4 and PyQt5 at the same time:
- Up to version 0.5 (i.e. master branch on github) we were on PyQt4
- From version 0.6 (work in progress on the develop branch) we switched to PyQt5 without support for PyQt4 anymore.

You can see all the adaptation work in this commit 56aa3015862f309dbcec09b3b62b68cee24770c7. Since this was the first thing we did when beginning work on v0.6, if you checkout this commit, you will technically have the current v0.5 version of ts2 running on PyQt5 instead of PyQt4. 

We don't plan to have a version that supports both PyQt4 and PyQt5, but if you want to code it, then I would be very happy to merge it. If you wish to do so, then I'd suggest you base your work on 56aa3015862f309dbcec09b3b62b68cee24770c7.

**Comment by pedromorgan** [comment]
Maybe we need to add words to that effect in the README on both branches.. ??
Or just do a quick release bumping master to Qt5 ??

**Comment by mcgiwer** [comment]
@npiganeau the code in the pyqt.py is a example solution how to check the code and import needed PyQt libs (it may be properly addapted). The remaining files would refer itself to it to import any PyQt and Qt related libs (in the example one I had imported the both: PyQtCore and PyQtGui). This way it would possible to get at latest partial backwards compatibility.

if you want then you can merge from my ts2 repo the polish translation for ts2


Is there a tested working with pyqt version of the ts2?

**Comment by mcgiwer** [comment]
@pedromorgan & @npiganeau Something is wrong with the repo. I try to do the pull request and I get the error that I don't have write permission to it. Could you check and fix it?

**Comment by npiganeau** [comment]
The merge request went fine. Thanks for the polish translation.

Sorry, I'm not sure I really understood what you meant with
> Is there a tested working with pyqt version of the ts2?

but I try to keep the ts2 version on the develop branch working at all times. I suggest you try it with gretz-armainvilliers simulation from ts2-data repository to get a view of the new features.

**Comment by npiganeau** [comment]
@pedromorgan You're right, I'll update the READMEs

**Comment by Sharpe49** [comment]
I don't think having a PyQt4 compatible version is  a good idea. It adds some complexity for... nothing Most Linux desktop environments are moving from Qt4 to Qt5 (example : KDE 5 and LXQt) and most distributions can handle having both installed at the same time.
Qt4 is now no longer maintained (besides some security fixes). No new development should be based on Qt4 !

**Comment by pedromorgan** [comment]
Guys.. Can I close this issue.. please..

I only joined the project a few months ago, .but there is a huge issue of (as part of day job)..
- python2.7 + Pyqt4
- python2.7 + Pyside
- python3 + Pyqt4 == current ts2 head (a strange combination)

NOTE Qt4 = square: 
- the Upstream c++ Qt4 is in maintanance mode.. no dev
- all the API's to Qt4, ie PyQt4 and PySide is moot, they are not in dev

NOTE Qt5 = triangle: 
- Qt5 c++ upstream is a major revamp and fixes a lot of things..
- Its a major change, not backward compatible, new c++ version and new kinbs, eg QJson
- With Pyqt5, the opportonity was taken to abandon python2+ series
- So PyQt5 runs on python3 only

You cannot stick a  square in a triangle.

python3 + PyQt5 is future
=================================
- A lot of conversion is done, HEAD develop is on pyqt5 (expect relase sooonn)
- and json for saving/loading data, so sqlite is out (#20)
- next step is to make stable release with pyqt5
- then expect things to ramp up with online server and sharing..

But guys please.. We wanna have fun dont we.. lets step up.. make a great sim.. raise more issues..

What in your wildest dream do u wan it to do ?

**Comment by npiganeau** [comment]
I think we all agree. I close.

**Comment by mcgiwer** [comment]
mayby the ts2 should be writen from scratch for PyQt5 or in other language (like by example C++ or Java to make it more universal instead of fixing whole time the newly created bugs?

**Comment by Sharpe49** [comment]
While I quite like the idea of using C++ (C++11 is the language I use the most, mainly with Qt5), I think that a rewrite would be quite long.
There will be improvements, for example better debuggers, better performance (well... TS2's performance is already great so this factor isn't really important), but python has a garbage collector which makes memory management... a joke (but for me, that just means I have to be more rigorous when I'm writing C++ code).
I think that such a choice would a bit difficult. But for the moment, the need to change... isn't really present... so...
