### ISSUE TITLE
Problems with the dev version of ts2

### ISSUE THREAD

**Issue by mcgiwer** [ts2/ts2#52]
I have a question. When do you plan to update the main application code to make it for PyQt5 as was planed? the actual application code in the "master" repo refers itself whole time to PyQt4.

May I offer that the simulator for PyQt5 could be named by example ts3 to reorganize the new version?

**Comment by npiganeau** [comment]
The new version will be released when we have finished the tasks in the roadmap (#46). This can take more or less time depending on our availability to code. For the record, it took 5 years between v0.2 and v0.3 and 2 years between v0.4 and v0.5 ...

But again (sorry for repeating myself) you don't need to wait for this release to have ts2 working in a pyqt5 environment: just check out develop branch and run.

**Comment by mcgiwer** [comment]
@npiganeau ok... it working, but kad found some errors:

* while starting:
$ ./start-ts2.py 
pl_PL
QMetaObject::invokeMethod: No such method QMenuBar::aboutToShow()
Traceback (most recent call last):
  File "/media/ubuntu/tmp/dane/repo/ts2-develop/ts2/mainwindow.py", line 429, in downloadSimulations
    with open(fName, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'simulations/drain.ts2'
QMetaObject::invokeMethod: No such method QMenuBar::aboutToShow()
QMetaObject::invokeMethod: No such method QMenuBar::aboutToShow()
QMetaObject::invokeMethod: No such method QMenuBar::aboutToShow()
Traceback (most recent call last):
  File "/media/ubuntu/tmp/dane/repo/ts2-develop/ts2/mainwindow.py", line 465, in showContextMenu
    if self.sender() == self._trainInfoView:
AttributeError: 'MainWindow' object has no attribute '_trainInfoView'
Traceback (most recent call last):
  File "/media/ubuntu/tmp/dane/repo/ts2-develop/ts2/mainwindow.py", line 465, in showContextMenu
    if self.sender() == self._trainInfoView:
AttributeError: 'MainWindow' object has no attribute '_trainInfoView'
Traceback (most recent call last):
  File "/media/ubuntu/tmp/dane/repo/ts2-develop/ts2/mainwindow.py", line 465, in showContextMenu
    if self.sender() == self._trainInfoView:
AttributeError: 'MainWindow' object has no attribute '_trainInfoView'

* while running:

-> editor-> activate - don't work
-> download simulations: after confirming the address, the busy cursor appears and nothing more happens

**Comment by npiganeau** [comment]
Create a simulations/ directory at the root of ts2 source and try again. We'll fix that.

**Comment by npiganeau** [comment]
I've just fixed the pb of editor not opening in ubuntu.
