### ISSUE TITLE
New >> 0.6 Release

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#60]
Can we move forward with a "point release"..

0.6 is the new qt5 etc..

We need to push this out asap..
So we can convert users into new pyqt land..

We need to do this soon and a critical list of  why not?

We also need to ge intoa  fast udpate methos..

But o.6 will be the test..

What is the stop lsit for vo.6.. afaik it works.. lets blow it..?

**Comment by npiganeau** [comment]
See #46

**Comment by pedromorgan** [comment]
irc.freenode.net#trainsigsim ..
with @npiganeau Sharpe49

Wwe need to blow a relase.. Its only gonna crash a few PC's and not blow up the world..

Lets have fun gus and make it upadate every week, ans everyone can winge and we get a comitte to sort it out..

Lets move to fast release, and more fast.. after we cahange to pyqt5

**Comment by pedromorgan** [comment]
From Now..
figure out pyqt5 release..

Make and freeze api and make pyqt5  release..

and release often

**Comment by npiganeau** [comment]
Sorry @pedromorgan, I'm as impatient as you are to see v0.6 out, but if we release it now, I won't have any incentive to code train splitting/joining (it was scheduled for v0.5 originally...).

Moreover, I have plans for v0.7 that will involve a new architecture to take into account #57 , #39 and #40 discussions (I'll give details this weekend), and if I start this before finishing the splitting/joining stuff we'll never have it!
