### ISSUE TITLE
IRC Chat = irc.freenode.net#trainsigsim

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#62]
FIY ;_))

And we got a bot clled ts2bot.. needs feeding ;-)

**Comment by pedromorgan** [comment]
Ok so this is showing commits at
```
irc://freenode.net#trainsigsim
```

At v0.6 we need to start promote this as it could be usefuland means adding to help et all

**Comment by mcgiwer** [comment]
@pedromorgan I messaged you many times on IRC but you didn't replied :p

**Comment by pedromorgan** [comment]
Sorry been thought a nightmare with olde nvdia.geforce.210 and kubuntu..

Its no working fantastic in xfce .. ;-))
