### ISSUE TITLE
Next arch = v0.7

### ISSUE THREAD

**Issue by npiganeau** [ts2/ts2#63]
Ok guys here's my plan for v0.7 taking into account several ideas you all had in #57 , #40 , #39 among others.

# Current situation
- GUI and simulation logic are mixed up (although I tried to separate them and make them talk through signal/slot mechanism, it is not always as clear). The monolithic construction of TS2 makes it hard for a newcomer to understand how it works.
- Namespaces are just awful. Just don't ask me why a file is inside a folder and not another one. And we have circular references which have been worked around in a very ugly manner...
- It's quite impossible to have several coders work at the same time on TS2 code.
- We all see the interest of having a software with a lot of interfaces so that it can be used as it is now (a signalling simulation game), but there are ideas of interfacing it with real model trains for example.

# New architecture
So after we have released v0.6, my idea is to split up the software following this arch:
![arch](https://cloud.githubusercontent.com/assets/3935559/10406132/1a113a0c-6ede-11e5-8ee7-455e84426bfc.png)

## TS2 sim server
This is the central piece of the software. It is shipped with the TS2 release.

It can be run:
- Locally for a standalone game (as it is now)
- Remotely on another PC or even on a cloud server for multi-player gaming

The TS2 sim server tasks are
- To centralize the game data, that is:
    - Scenery layout (The track items, and how they are connected to each other, their states, etc.)
    - Possible and set routes
    - Services and Trains
- To enforce interlocking by calling in turn the appropriate inputs simulator on : 
    - Route setting/unsetting 
    - Change of points position
    - Update of signals aspects
- Make the clock tick

The TS2 sim server communicates with other TS2 components through websocket.

Initial game data can be downloaded from TS2 data server (through standard http, like it works now) or uploaded from client (e.g. saved game), depending on user choice

The TS2 sim server has no UI and will not depend on Qt or any of its binding. Programming language to be defined.

## TS2 clients
TS2 clients will be in charge of user interface:

The reference client will be a PyQt client adapted from the current TS2 software.

Other clients can be imagined :
- Webclient (at least to display time tables or make presentations)
- Android/iOS clients
- "Near reality" clients in order to have the look&feel of real signalling centres, depending on countries/technologies

## TS2 editor
The editor is not really a client since it does not need to communicate with the ts2 sim server. However, I will probably keep it inside the PyQt client since they share many classes.

## TS2 Inputs simulators
These will be independent services that are in charge of simulating all the inputs that we have in real life and that are not in a simulation.

There are different input simulators, and each can have different implementations. The implementation to use will be defined in the simulation JSON definition.

Each inputs simulator will be able to register to specific events at the TS2 sim server to be notified only when necessary.

The inputs simulators have no UI and will not depend on Qt or any of its binding. Programming language to be defined for each.

### Trains inputs simulator
This inputs simulator is in charge of calculating the trains positions at each clock tick from data sent by the TS2 sim server and send the info back to the sim server.

The reference train inputs simulator will be derived from the current TS2 implementation.

Other implementation may include getting the info of position from a model train set or even from real railway timetables.

### Trackitems inputs simulator(s)
This inputs simulator's main task is to send back the status of a trackitem after a command. It is both : 
- an output interface through which every command to track items are sent
- an input interface for the feedback, which enable simulating breakdowns

Eg. When the TS2 sim server will be requested to move points, it will send the command to the trackitems simulator. The latter will respond with the points position (potentially after a delay of a few seconds).

Each type of track item can use a different implementation fo trackitems inputs simulator.

The reference implementations will be:
- A signalItem inputs simulator derived from the current signalLibrary mechanism in TS2 for signals
- An 'always return True' inputs simulator for other items (no breakdown) at first.

Other implementations can include : 
- Sending the output to model railway through arduino 
- Responding with more or less breakdown probability

### Routes inputs simulator
This inputs simulator's tasks are:
- To enforce route interlocking by responding to the TS2 sim server whether the route can be set/unset or not after request.
- To destroy the route after train passes if the route is not persistent

The reference implementation will be derived from the current TS2 software.

### ARS inputs simulator
This is the 'Automatic Routing System' inputs simulator. It is a software by itself which looks up in the TS2 sim server for info and sets up routes according to its built-in rules.

Several implementations of ARS can be imagined to reflect different countries/technologies.

## TS2 data server
This is the server for storing/exchanging simulation files. It is the extension of ts2-data repository.

This part of the project is not impacted by the new architecture.

# What's next ?
Well, on my side, I will continue to work to make train splitting/joining work before we release v0.6 (sorry for the impatient, but I really want to achieve this before).

Then I'll define precisely the protocol for websocket communication between the TS2 components so that if any of you is particularly interested in coding one of them, he can start doing so.

**Comment by pedromorgan** [comment]
Fantastic.. am still digesting.. but kinda the idea your on about is similar/parallel.. ;-))

BTW: I know limitations of how to knock up an idea, and make it work.. and hacking together.. but things  and on review  wrong place api etc etc.. so @npiganeau thanks.. (and how did u make diagram ?)

Also I add we wan to replicate "real life" somewhat.. and this is from hacking flightgear
- where weather has an effect
- a line is closed because tree
- and alike.. then we can have real fun..
- and time is in UTC and a tick that runs, normally at > 50fps
  - METAR = weather - so be can create frozen/leaves no brake or heated bent tracks..

But lets have fun, this is cool.. I'm in ;-))))))))

**Comment by pedromorgan** [comment]
Re saving Game.. Lets not focus at that for now imho..
- We can restore state later but lets ntot focus on that now imho
- lets make sim work correct

**Comment by pedromorgan** [comment]
So we basically gonna use the shite from Flightgear..

So sending signals, and recieving..

Everything is in the "sim", including the "axle counter" and the Fibre optic
- maybe we create a peace train thqat runs from calais to syria and back.. with current refugee..

**Comment by pedromorgan** [comment]
Has anyone done this already ??
Can we take other sims data files for import ?

**Comment by pedromorgan** [comment]
Actually reading it again.. Yes.. its kinda spot on in the way we can make it move forward..

- THe general idea is to make each element a seperate "connected" thingi..
- And make then react and sned/rcv too a sim..
- And actually pugggiable.
- Its actally removing some qt signal/slot and making a network instead..
- This is the way to go and more of a reflection of the real time sim..
- @npiganeau has set the foundation and it works... as a proto.. .. and halleluauaiag. now lets go mad and it really work.. complaints required. ;-)

**Comment by npiganeau** [comment]
@pedromorgan Yes, you've got the idea. 

I close the issue since I moved all the info on the wiki
