### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#65]
Develop has a problem,
with the liverpool from download

```
Traceback (most recent call last):
  File "/home/ts2/ts2/ts2/trains/train.py", line 805, in activate
    signalAhead = self.findNextSignal()
  File "/home/ts2/ts2/ts2/trains/train.py", line 1073, in findNextSignal
    nsp, nsd = self.getNextSignalInfo(pos)
  File "/home/ts2/ts2/ts2/trains/train.py", line 1051, in getNextSignalInfo
    if pos == None:
  File "/home/ts2/ts2/ts2/routing/position.py", line 321, in __eq__
    return (self._trackItem == p.trackItem and
AttributeError: 'NoneType' object has no attribute 'trackItem'
```

Now I am not sure whats happening and investegations, and diving deep into the bowels of something I dont quite understand.. yet..

**Comment by pedromorgan** [comment]
In fact its happening on all the sims..

**Comment by Sharpe49** [comment]
Reported here also : 
https://github.com/ts2/ts2-data/issues/3

**Comment by pedromorgan** [comment]
Umm ..
```py
        if pos == None:
            pos = position.Position()
        retPos = position.Position()
        retDist = -1
        if pos == position.Position():
            pos = self._trainHead
```

This looks suspicuius
```py
if pos == position.Position():
```
Is trying to compare a blank instance against other.. Does this compare instances ??
https://github.com/ts2/ts2/blob/develop/ts2/trains/train.py#L1051

**Comment by npiganeau** [comment]
Error comes from 3073b8a304494826506b8d65f22e4f64ff3eb00d

@pedromorgan None should be tested through ```if a is None``` and not ```if a == None```

Fixed with commit above

**Comment by pedromorgan** [comment]
yep ;-))
