### ISSUE TITLE
Feature Request: zones

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#74]
I am playing with gretz/villiers sim and a few things..
#1) Station

A station, is some platform and the test..
Clicking on a "platform "
shows the TOURNAN station info..

So what I kinda want to do  is make the "whole Tournan" station a hot spot.. group
so click upon and see data in station info..

leads to ...
#2) Zones

We cant have llong multispan screens, out lowest in once screen..
I have two of different dimenstion.. etc on ubuntu/xfce (bye Kubuntu after last update)

So maybe we can create "zones", eg a station area etc
and these are prsented in the sim under the main "Graphics"

So there is a kinda strip down the bottom of the "zones" / sections..
and move's scroll t it..

I'm not sure how to do this, but maybe a "smallish" version of the main screen in little bits..
Cant explain... 
but It would mean meaking a "split into zone"
of station, its approach and departure..
Much like ATC control to an Airport in FlightGear..

**Comment by pedromorgan** [comment]
Question..

How so we create a "order" of stations ?

What I kinda invisage is banging in a list of stations
and their platforms also "uniquely ordered"

**Comment by pedromorgan** [comment]
Maybe we can parse the "ts2" data and dynamically create svg ;-) ..

Now that tickles me.. dont know why... though..

**Comment by npiganeau** [comment]
Stations are Places (though all places are not stations...).

Platform after linked to places, so you can have several platforms linked to the same station (see place code property). So clicking on any platform of the station gives the station info.

**Comment by pedromorgan** [comment]
Yep, platform, but not the text..
So these need to be grouped..
as in liverpool..

and then the arrivals/departures boards..

**Comment by pedromorgan** [comment]
Same with "tunnel" in liverpool..
We need to create a "Supervilous" item to represet tunnels and bridge etc
Not part of signal.. maybe but a "label" and zone..
