### ISSUE TITLE
Issues in ts2 v0.6

### ISSUE THREAD

**Issue by mdziczkowski** [ts2/ts2#75]
When trying to start the 0.6, I'm getting following output (even if I have Python 3+ installed):

$ python ./start-ts2.py 
- Qt: Session management error: None of the authentication protocols specified are supported
  pl_PL
- This simulation uses 'UK_4_ASPECTS' signal types which are not available on this computer. You can download the missing files from the server in File->Open dialog (when trying to open the "London Liverpool Street" after downloading all sims)
- in editor the scrolling don't work correctly

**Comment by npiganeau** [comment]
you  need to install simple-json

Either:
```pip install simplejson```

or 

```apt-get install python3-simplejson```

if you're on a debian based distro

I need to update the README with this one.

**Comment by mcgiwer** [comment]
@npiganeau I fixed the simplejson issue by re-installing the lib. After that, new issues apeared (edited my post)

**Comment by pedromorgan** [comment]
@mcgiwer did you get it working ?
