### ISSUE TITLE
New Developers TODO

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#78]
Yo all, and newbies,

Here's how to get hacking on a complete rewrite with a new "network architecture"..
- idea is to.. instead having a desktop application and logic embedded.. binded together...
- Next step is to split all stuff up.. see new_arch..

So whatever your talents and requirements.. 

PLEASE Take your pick ;-))

- Loading a simulation and all its stock, routes etc
- Central sim-server = new version in golang and websockets.
- Pyqt websocket client
- android client
- ionic client
-

**Comment by npiganeau** [comment]
@pedromorgan Happy new year! I've not be in recently, new born baby at home makes things difficult for ts2. 

I've just added a developers todo in the wiki.

Also, sim server step 1 is almost done on nextarch branch.

**Comment by pedromorgan** [comment]
https://github.com/ts2/ts2/wiki/Developers-TODO
