### ISSUE TITLE
Status update?

### ISSUE THREAD

**Issue by StigHetl** [ts2/ts2#80]
I don't know if this was the right place to ask this question, but I couldn't find any other discussion forum. 

What's the status of ts2? How's the development going?

Thank you!

**Comment by pedromorgan** [comment]
Basic rundown....i got involved a year ago ishh..

- Ts2 has moved from SF.net to
- https://github.com/ts2 = ts2 project

The project was migrated from 
- Pyqt4 
- Pyqt5 which is what current realse is
- at the new website.. http://ts2.github.io/

However, the current "master branch" and latest is the last in series,,
and is indeed being rewritten in 
- golang for sim code
- and whatever we want for "presentation code"
- A New "Archicetrure"..
-- https://github.com/ts2/ts2/wiki/New-Arch

So most recent code is in
https://github.com/ts2/ts2-sim-server
the new simulation, websocket connect ts2 server..
and all clients intergrate with that..

if @npiganeau was around then he can code the shole thing in a night.. even ;-)))))))) 

@StigHetl U usung latest version ?? more feedback appreciated

**Comment by npiganeau** [comment]
Hi @StigHetl ,

Well, development is ongoing but at a variable pace, depending on my time... As I always say, it took 5 years between the very first usable version (0.2) and the next (0.3). Now we are at 0.6 which is the master branch. Except for a few possible bugs it should be playable, but we don't have much sims for the moment.

As said @pedromorgan next step is v0.7 which is a major rewrite with a modular and network centric architecture which will permit cool things such as multi-player or interfacing ts2 with other software or even real model railways (@pedromorgan 's dream...).

Sometimes I'm very motivated and things are going quite well, other times, such as now, I'm overbooked by work and other projects and it just sits there ...

**Comment by Sharpe49** [comment]
Hello @npiganeau ,

Is the project dead ?

**Comment by npiganeau** [comment]
Hello @Sharpe49 

Well, perhaps the project is not dead, but it is undeniably sleeping deeply.
Actually, most of my time is taken for another project and that will be the case at least until this summer.

Now if we are several people interested in waking up TS2, that might help my motivation :-)

**Comment by pedromorgan** [comment]
@npiganeau From my point of view, what's holding progress back a having a having a basic websocket send/recv (eg the clock) and how you see that in code (channels etc). From there I reccon I can help with the editing trains/services etc...
