### ISSUE TITLE
Editor - issue with (un)linked items

### ISSUE THREAD

**Issue by timmie1606** [ts2/ts2#88]
Trying to make a sim, when saving it you can get 'Invalid simulation: Not all items are linked or end items are missing'.
Is there a way to find where the problem is (something like a highlighter)?
Otherwise i'd definetely recommend this for the next release

**Comment by npiganeau** [comment]
Unfortunately not. But I note the proposal.

Most of the time, this is when an "end item" is missing (item with just a dot inside that must be put on the free end of each item at the edge of your layout so that all items are linked to something)

**Comment by timmie1606** [comment]
Well, that's just the thing, i have end items everywhere but still get an error

**Comment by timmie1606** [comment]
I put it in a wetransfer
Here's the download link:
https://wetransfer.com/downloads/2bf13c074ed06b15edc1b6c0ff7093c320180411133900/26073a7066721808ae268643da8d069820180411133901/20e7d7
It might look big and ambitious, but i did actually started learning building with a smaller simulation.
My guess is that there's a hidden tracksegment or point somewhere (under something else)

**Comment by npiganeau** [comment]
Track 3: LineItem id226 is not connected on its left to the buffer id281 (one grid step difference)

**Comment by npiganeau** [comment]
Now you have a pb at position (1380, 190), that's on track 11, roughly half way between the station and the tunnel where two points overlap.

**Comment by timmie1606** [comment]
Ok. Thanks, Completely fixed now. validation succesful.
