### ISSUE TITLE
Editor - signal type not readable 

### ISSUE THREAD

**Issue by timmie1606** [ts2/ts2#89]
I can not read the full discription of the signal type.
See picture.
For future release this should be better, i think
[
![naamloos](https://user-images.githubusercontent.com/38163662/38676690-1b9ae210-3e5c-11e8-9bcb-2b3f840862cc.png)
](url)

**Comment by npiganeau** [comment]
You can increase the size of the column by pulling the right edge of the header "Value" to see the whole list.
