### ISSUE TITLE
Print signal number next to the signal

### ISSUE THREAD

**Issue by npiganeau** [ts2/ts2#99]
In small. Add an option to display or not.

**Comment by npiganeau** [comment]
No option added. If we need not to show a signal number, just set its name to blank.

**Comment by Sharpe49** [comment]
The result seems a bit random.

![2019-12-22 21_32_37-ts2 - Train Signalling Simulator - Gretz-Armainvilliers](https://user-images.githubusercontent.com/375720/71326977-c09e8d00-2502-11ea-9457-b5265b8e6816.png)

**Comment by npiganeau** [comment]
I take first 5 characters of signal name. I need a fixed number because depending on the signal direction, I have to wrap left or right.

Do you need more characters? How many?
